import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { v7 as uuidv7 } from 'uuid'
import { HttpError, getGeneralSettings, getProductById, getSuggestions, makeEvent, sendEventStream } from './api'
import { Composer } from './components/Composer'
import { DebugPanel } from './components/DebugPanel'
import { Header } from './components/Header'
import { MessageList } from './components/MessageList'
import { Onboarding } from './components/Onboarding'
import { LS, readJSON, readOrCreate, writeJSON } from './storage'
import type {
  AssistantCarouselEvent,
  AssistantQuickReplyEvent,
  AssistantTextEvent,
  ChatEvent,
  GeneralSettings,
  MetadataSelectAgentEvent,
  OnboardingConfig,
  OutboundEventInput,
  ConversationStarter,
  RenderMessage,
} from './types'
import { getEnvOnboarding, isUserVisibleUserEvent, translate, userEventText, uuid } from './utils'

const SUGGESTIONS_DEBOUNCE_MS = 300
const SUGGESTIONS_LIMIT = 5
// Search-sample fallback placeholders shown before chat starts on an empty
// search/autosuggest surface. PDP and PLP clients should use the contextual
// conversation-starter endpoints instead of these hard-coded sample values.
const SEARCH_FALLBACK_STARTER_QUESTIONS: ConversationStarter[] = [
  'What can you help me find?',
  'What are your most popular products?',
  'Can you recommend something for me?',
  'How do I choose the right product?',
  'What should I know before buying?',
].map((text) => ({ text, label: text }))

function getUserFacingErrorMessage(error: unknown, t: (key: string, fallback: string) => string): string {
  if (error instanceof HttpError) {
    if (error.status === 429) return 'Something went wrong, please try again in a minute.'
    if (error.status >= 500) return 'Something went wrong, please try again later.'
    if (error.status === 400) {
      console.error('Bad send-event request generated by sample client', error)
      return t('tryAgain', 'Please try again.')
    }
    return t('errorMsg', 'Something went wrong. Please try again.')
  }

  if (error instanceof DOMException && error.name === 'AbortError') {
    return t('errorMsg', 'The assistant took too long to respond. Please try again.')
  }

  if (error instanceof TypeError) return `${error.message}. This may be a network or CORS issue.`
  if (error instanceof Error) return error.message
  return 'Unknown error'
}

export default function App() {
  const [config, setConfig] = useState<OnboardingConfig | null>(() => readJSON(LS.onboarding) ?? getEnvOnboarding())
  const [endCustomerId, setEndCustomerId] = useState(() => readOrCreate(LS.endCustomerId, uuid))
  const [chatId, setChatId] = useState(() => readOrCreate(LS.chatId, uuid))
  const [settings, setSettings] = useState<GeneralSettings | null>(null)
  const [messages, setMessages] = useState<RenderMessage[]>([])
  const [debugEvents, setDebugEvents] = useState<ChatEvent[]>([])
  const [progressText, setProgressText] = useState<string | null>(null)
  const [activeAgent, setActiveAgent] = useState<string | null>(null)
  const [inflight, setInflight] = useState(false)
  const [fatal, setFatal] = useState(false)
  const [debugOpen, setDebugOpen] = useState(false)
  const [onboardingError, setOnboardingError] = useState<string | null>(null)
  const [composerText, setComposerText] = useState('')
  const [suggestionStarters, setSuggestionStarters] = useState<ConversationStarter[]>([])
  const startupRanFor = useRef<string | null>(null)

  const disabled = inflight || fatal
  const trimmedComposerText = composerText.trim()
  const displayedStarters = trimmedComposerText
    ? suggestionStarters
    : messages.length === 0
      ? SEARCH_FALLBACK_STARTER_QUESTIONS
      : []
  const startersHeading = trimmedComposerText ? 'Conversation starters' : 'Try asking'

  const t = useCallback((key: string, fallback: string) => translate(settings, key, fallback), [settings])

  const appendMessage = useCallback((message: RenderMessage) => {
    setMessages((current) => {
      if (current.some((item) => item.id === message.id)) return current
      return [...current, message]
    })
  }, [])

  const sendEvent = useCallback(
    async (
      input: OutboundEventInput,
      options: { showOptimistic?: boolean; userInitiated?: boolean } = {},
    ) => {
      if (!config) return
      const isUserInitiated = options.userInitiated ?? input.type.startsWith('ADD_MESSAGE.USER.')
      if (isUserInitiated && inflight) return

      const event = makeEvent(input)
      if (options.showOptimistic !== false && event.type.startsWith('ADD_MESSAGE.USER.')) {
        appendMessage({ id: event._id, kind: 'user', text: userEventText(event), raw: event })
      }

      if (isUserInitiated) {
        setInflight(true)
        setProgressText(settings?.staticReplies?.notificationThinking || t('notificationThinking', 'Thinking…'))
      }

      try {
        await sendEventStream({
          config,
          chatId,
          endCustomerId,
          event,
          onEvent: (item) => handleInboundEvent(item as ChatEvent),
        })
      } catch (error) {
        const message = getUserFacingErrorMessage(error, t)
        appendMessage({ id: uuidv7(), kind: 'error', text: message })
      } finally {
        // Clear the progress indicator only now that the whole turn is
        // complete (all response events received). It is intentionally kept
        // visible while messages stream in, so this is the single place it is
        // removed on success.
        setProgressText(null)
        if (isUserInitiated) setInflight(false)
      }
    },
    // handleInboundEvent intentionally reads latest state through React setters and stable helpers.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [appendMessage, chatId, config, endCustomerId, inflight, settings, t],
  )

  const handleInboundEvent = useCallback(
    async (event: ChatEvent) => {
      switch (event.type) {
        case 'ADD_MESSAGE.ASSISTANT.NOTIFICATION':
          setProgressText(typeof event.text === 'string' ? event.text : '')
          break

        case 'ADD_MESSAGE.ASSISTANT.TEXT':
        case 'ADD_MESSAGE.ASSISTANT.COLD_START':
          appendMessage({ id: event._id, kind: 'assistant', text: (event as AssistantTextEvent).text || '', raw: event })
          break

        case 'APPEND_LAST_ASSISTANT_MESSAGE':
          setMessages((current) => {
            const lastAssistantIndex = [...current].reverse().findIndex((message) => message.kind === 'assistant')
            if (lastAssistantIndex === -1) {
              return [...current, { id: event._id, kind: 'assistant', text: (event as AssistantTextEvent).text || '', raw: event }]
            }
            const index = current.length - 1 - lastAssistantIndex
            return current.map((message, messageIndex) =>
              messageIndex === index && message.kind === 'assistant'
                ? { ...message, text: `${message.text}${(event as AssistantTextEvent).text || ''}` }
                : message,
            )
          })
          break

        case 'ADD_MESSAGE.ASSISTANT.CAROUSEL': {
          const carousel = event as AssistantCarouselEvent
          const products = carousel.data ?? []
          const enrichedProducts = await Promise.all(
            products.map(async (product) => {
              if (product.image) return product
              try {
                const response = await getProductById(config!, product.id, { skipQuestionSelection: true })
                const data = response.response.item?.data
                const image = typeof data?.thumb_image === 'string' ? data.thumb_image : null
                return image ? { ...product, image } : product
              } catch (error) {
                console.warn(`Could not load image for product ${product.id}`, error)
                return product
              }
            }),
          )
          appendMessage({ id: event._id, kind: 'carousel', products: enrichedProducts, raw: carousel })
          break
        }

        case 'ADD_MESSAGE.ASSISTANT.QUICK_REPLY':
          appendMessage({
            id: event._id,
            kind: 'quickReply',
            text: (event as AssistantQuickReplyEvent).text,
            replies: (event as AssistantQuickReplyEvent).data ?? [],
            raw: event as AssistantQuickReplyEvent,
          })
          break

        case 'METADATA.SELECT_AGENT':
          setActiveAgent((event as MetadataSelectAgentEvent).agent || null)
          break

        case 'ERROR':
        case 'FE.SET_CONTEXT':
        case 'SELECTED_ITEMS':
          break

        case 'FATAL_ERROR':
          setProgressText(null)
          appendMessage({ id: event._id, kind: 'error', text: t('errorMsg', 'Something went wrong. Please try again.'), fatal: true, raw: event })
          setFatal(true)
          break

        default:
          // Anything not handled above falls through here and is ignored unless it is a
          // user event worth echoing. Required by the contract: the stream also carries
          // internal event types excluded from openapi-spec.json, and new ones may be
          // added without that being a breaking change. Never throw here.
          if (isUserVisibleUserEvent(event.type)) {
            appendMessage({ id: event._id, kind: 'user', text: userEventText(event), raw: event })
            break
          }
          // Unrecognised: dropped entirely, debug panel included.
          return
      }

      setDebugEvents((current) => [...current, event])
    },
    [appendMessage, config, t],
  )

  useEffect(() => {
    setSuggestionStarters([])
    if (!config || fatal) return
    const query = composerText.trim()
    if (!query || query.length < 2) return

    const abort = new AbortController()
    const timer = window.setTimeout(() => {
      getSuggestions(config, query, { limitQuestions: SUGGESTIONS_LIMIT, limitKeywords: 0, signal: abort.signal })
        .then((body) => {
          const starters = (body.response.suggestions?.questions ?? [])
            .map((question) => ({
              text: question.question || question.mini_question || '',
              label: question.mini_question || question.question || '',
            }))
            .filter((starter): starter is ConversationStarter => Boolean(starter.text && starter.label))
            .slice(0, SUGGESTIONS_LIMIT)
          setSuggestionStarters(starters)
        })
        .catch((error) => {
          if (abort.signal.aborted) return
          console.warn('conversation-starter suggestions failed', error)
          setSuggestionStarters([])
        })
    }, SUGGESTIONS_DEBOUNCE_MS)

    return () => {
      window.clearTimeout(timer)
      abort.abort()
    }
  }, [composerText, config, fatal])

  useEffect(() => {
    if (!config) return
    const key = `${config.apiUrl}|${config.agentId}|${config.apiToken}|${config.currency}|${chatId}`
    if (startupRanFor.current === key) return
    startupRanFor.current = key

    const activeConfig = config
    // Staleness is tracked through startupRanFor rather than a cleanup flag.
    // Under React.StrictMode the effect is mounted, torn down and mounted
    // again; a cleanup flag would cancel the only boot that ever starts, since
    // the second mount short-circuits on the matching key. Comparing the ref
    // instead keeps the boot alive across that remount while still abandoning
    // it once the config or chatId really changes.
    const isStale = () => startupRanFor.current !== key
    async function boot() {
      try {
        const loadedSettings = await getGeneralSettings(activeConfig)
        if (isStale()) return
        setSettings(loadedSettings)
        setOnboardingError(null)
        await sendEvent({ type: 'FE.SET_CONTEXT', currency: activeConfig.currency }, { showOptimistic: false, userInitiated: false })
        if (!isStale()) await sendEvent({ type: 'SYNC_EVENT_LOG' }, { showOptimistic: false, userInitiated: false })
      } catch (error) {
        if (isStale()) return
        setOnboardingError(error instanceof Error ? error.message : 'Could not load persona settings')
        // Release the guard so re-submitting the same onboarding values boots again.
        startupRanFor.current = null
        setConfig(null)
      }
    }

    void boot()
  }, [chatId, config, sendEvent])

  const onOnboardingSubmit = (nextConfig: OnboardingConfig, nextEndCustomerId: string) => {
    writeJSON(LS.onboarding, nextConfig)
    const effectiveEndCustomerId = nextEndCustomerId || uuid()
    localStorage.setItem(LS.endCustomerId, effectiveEndCustomerId)
    setConfig(nextConfig)
    setEndCustomerId(effectiveEndCustomerId)
    setChatId(readOrCreate(LS.chatId, uuid))
    setMessages([])
    setDebugEvents([])
    setFatal(false)
    setInflight(false)
    setComposerText('')
    setSuggestionStarters([])
  }

  const newChat = () => {
    const previous = chatId
    const next = uuid()
    localStorage.setItem(LS.chatId, next)
    const history = readJSON<{ chatId: string; archivedAt: string }[]>(LS.chatHistory) ?? []
    writeJSON(LS.chatHistory, [...history, { chatId: previous, archivedAt: new Date().toISOString() }])
    setChatId(next)
    setMessages([])
    setDebugEvents([])
    setProgressText(null)
    setActiveAgent(null)
    setFatal(false)
    setInflight(false)
    setComposerText('')
    setSuggestionStarters([])
  }

  const reset = () => {
    localStorage.removeItem(LS.onboarding)
    localStorage.removeItem(LS.chatId)
    setConfig(null)
    setSettings(null)
    setMessages([])
    setDebugEvents([])
    setFatal(false)
    setInflight(false)
    setComposerText('')
    setSuggestionStarters([])
  }

  const onStarterClick = (starter: ConversationStarter) => {
    setComposerText('')
    setSuggestionStarters([])
    void sendEvent({ type: 'ADD_MESSAGE.USER.TEXT', text: starter.text })
  }

  const onQuickReply = (reply: { label: string; target?: string | null; payload?: Record<string, unknown> | null }) => {
    // Quick-reply selections are ALWAYS sent as DIRECT_CALL — never USER.TEXT
    // — regardless of the target/payload value. Copy any server-provided
    // target/payload back verbatim; send just the label when neither is set.
    void sendEvent({
      type: 'ADD_MESSAGE.USER.DIRECT_CALL',
      target: (reply.target ?? null) as never,
      payload: reply.payload ?? null,
      text: reply.label,
    } as OutboundEventInput)
  }

  const simulateHttpError = (status: 400 | 429 | 500) => {
    const message = getUserFacingErrorMessage(new HttpError(status, status === 429 ? 'Too Many Requests' : 'Simulated'), t)
    appendMessage({ id: uuidv7(), kind: 'error', text: message })
  }

  const content = useMemo(() => {
    if (!config) {
      return (
        <Onboarding
          initialConfig={readJSON(LS.onboarding) ?? getEnvOnboarding()}
          initialEndCustomerId={endCustomerId}
          error={onboardingError}
          onSubmit={onOnboardingSubmit}
        />
      )
    }

    return (
      <div className="screen active chat-screen">
        <Header
          settings={settings}
          activeAgent={activeAgent}
          onNewChat={newChat}
          onToggleDebug={() => setDebugOpen((open) => !open)}
          onReset={reset}
        />
        <MessageList
          messages={messages}
          progressText={progressText}
          settings={settings}
          currency={config.currency}
          disabled={disabled}
          onQuickReply={onQuickReply}
        />
        <Composer
          settings={settings}
          disabled={disabled}
          starters={displayedStarters}
          startersHeading={startersHeading}
          onTextChange={setComposerText}
          onStarterClick={onStarterClick}
          onSubmit={(text) => {
            setComposerText('')
            setSuggestionStarters([])
            void sendEvent({ type: 'ADD_MESSAGE.USER.TEXT', text })
          }}
        />
        <DebugPanel open={debugOpen} events={debugEvents} onSimulateHttpError={simulateHttpError} />
      </div>
    )
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeAgent, config, debugEvents, debugOpen, disabled, displayedStarters, endCustomerId, messages, onboardingError, progressText, settings, startersHeading])

  return content
}
